name: read_y
description: Read-y app

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  firebase_auth: ^3.3.17
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0