name: read_y
description: Read-y app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  sqflite: ^2.0.2+1
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  html: ^0.15.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  objectbox: ^1.4.1
  objectbox_flutter_libs: any
  expandable_text: 2.2.0
  url_launcher: ^6.0.20
  flutter_svg: ^1.0.3
  flutter_swiper_null_safety: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  drift_dev: ^1.5.2
  build_runner: ^2.1.8
  objectbox_generator: any


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/readydb.db
    - assets/test.db