name: read_y
description: Read-y app

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.2
  firebase_auth: ^3.3.17
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  equatable: ^2.0.3
  webview_flutter: ^3.0.4
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0